// Generated by CoffeeScript 1.12.2
(function() {
  var ActivateFunc, Net, Variable, VariableOf, W, W_tanh, b, jam, nj, tanh_mapped;

  jam = require('./jam');

  nj = require('numeric');

  Variable = (function() {
    "Basic brick in neuron network.";
    function Variable(num_row, num_col, option) {
      var _, column_vector, initializer;
      if (option == null) {
        option = {};
      }
      this._c_param = {
        num_col: 0,
        num_row: 0,
        is_vector: false
      };
      this._m_state = {
        data: [[0]]
      };
      if (num_row instanceof Array && typeof num_row[0] === 'number') {
        column_vector = num_row;
        this._c_param.num_col = 1;
        this._c_param.num_row = column_vector.length;
        this._c_param.is_vector = true;
        this._m_state.data = column_vector;
      } else {
        this._c_param.num_col = num_col;
        this._c_param.num_row = num_row;
        this._c_param.is_vector = false;
        initializer = option.initializer;
        if ((initializer != null) && isNaN(initializer())) {
          throw TypeError("Error: initializer :: Void -> Double");
        }
        this._m_state.data = (function() {
          var i, ref, results;
          results = [];
          for (_ = i = 0, ref = num_row; 0 <= ref ? i < ref : i > ref; _ = 0 <= ref ? ++i : --i) {
            results.push((function() {
              var j, ref1, results1;
              results1 = [];
              for (_ = j = 0, ref1 = num_col; 0 <= ref1 ? j < ref1 : j > ref1; _ = 0 <= ref1 ? ++j : --j) {
                results1.push((typeof initializer === "function" ? initializer() : void 0) || 0);
              }
              return results1;
            })());
          }
          return results;
        })();
      }
      this;
    }

    Variable.property('num_col', {
      get: function() {
        return this._c_param.num_col;
      }
    });

    Variable.property('num_row', {
      get: function() {
        return this._c_param.num_row;
      }
    });

    Variable.property('is_vector', {
      get: function() {
        return this._c_param.is_vector;
      }
    });

    Variable.property('data', {
      get: function() {
        return this._m_state.data;
      }
    });

    Variable.prototype.toString = function() {
      return "[Variable Object] Size: " + this._c_param.num_row + "x" + this._c_param.num_col;
    };

    Variable.prototype.map = function(f) {
      if (!(this instanceof Variable)) {
        throw TypeError("Error: this :: (Variable x)");
      }
      if ((f != null) && isNaN(f(0.0))) {
        throw TypeError("Error: f :: Double -> Double");
      }
      if (this._c_param.is_vector === true) {
        this._m_state.data = this._m_state.data.map(function(x) {
          return f(x);
        });
      } else {
        this._m_state.data = this._m_state.data.map(function(x) {
          return x.map(function(x) {
            return f(x);
          });
        });
      }
      return this;
    };

    return Variable;

  })();

  VariableOf = function(num_row, num_col, option) {
    return new Variable(num_row, num_col, option);
  };

  ActivateFunc = (function() {
    "Activate functions.";
    function ActivateFunc() {}

    ActivateFunc.prototype.tanh = function(x) {
      return Math.tanh(x);
    };

    return ActivateFunc;

  })();

  Net = (function() {
    "Neuron network.";
    function Net() {}

    return Net;

  })();

  W = VariableOf(2, 3, {
    'initializer': function() {
      return -0.1;
    }
  });

  b = VariableOf(1, 3);

  tanh_mapped = jam.map(ActivateFunc.prototype.tanh);

  W_tanh = tanh_mapped(W);

  console.log(W.data, W.toString());

}).call(this);

//# sourceMappingURL=app.js.map
