// Generated by CoffeeScript 1.12.2
(function() {
  var jam,
    slice = [].slice;

  jam = {};

  jam.curry = function(f) {
    var sub_curry;
    sub_curry = function(prev) {
      return function() {
        var args, curr;
        args = 1 <= arguments.length ? slice.call(arguments, 0) : [];
        curr = prev.concat(args);
        if (curr.length < f.length) {
          return sub_curry(curr);
        } else {
          return f.apply(null, curr);
        }
      };
    };
    return sub_curry([]);
  };

  jam.compose = function() {
    var fs;
    fs = 1 <= arguments.length ? slice.call(arguments, 0) : [];
    return function(x) {
      return fs.reduce(function(acc, val) {
        return acc(val(x));
      });
    };
  };

  jam.map = function(f) {
    return function(x) {
      return x.map(f);
    };
  };

  Function.prototype.property = function(prop, desc) {
    return Object.defineProperty(this.prototype, prop, desc);
  };

  if (module.exports != null) {
    module.exports = jam;
  } else {
    this.jam = jam;
  }

}).call(this);

//# sourceMappingURL=jam.js.map
